# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db5edc4a2b8acf5dff2394f8273f7a358c7ddd60db9837c4c97cf327ed3fb78c5f3df836f095f00a3ada57d376c628c6f8bb27c39d0bd2005e8bf3974e7beaf0

test:
  secret_key_base: ee25504e409de2fb2704586778c64636ded2c7d9e28788a60036a906822e2214dcbe4e845a51018393a00fdc938fdb735f99b50cab3b136f5ce2bb9e1b039ab9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
